### ISSUE TITLE
No inventory at provided URL

### ISSUE THREAD

**Issue by flying-sheep** [bskinn/sphobjinv#105]
```console
$ curl -I 'https://docs.h5py.org/en/stable/objects.inv'
HTTP/2 200 
date: Thu, 23 Jan 2020 16:15:59 GMT
content-type: application/octet-stream
content-length: 2065
...
$ `sphobjinv co plain -u 'https://docs.h5py.org/en/stable/objects.inv'`
No inventory at provided URL.
Attempting "https://docs.h5py.org/en/stable/objects.inv/objects.inv" ...
Attempting "https://docs.h5py.org/en/stable/objects.inv" ...
Attempting "https://docs.h5py.org/en/objects.inv" ...
Attempting "https://docs.h5py.org/objects.inv" ...
 
No inventory found!
```

`curl -I --http1.0` also works, no idea what fails here…

**Comment by bskinn** [comment]
Bah, yeah, I've seen this before -- some of the documentation websites have added some kind of filter to incoming traffic, which blocks the `urllib.request` requests that `sphobjinv` uses.  Looks like I really have to figure this out.

Related, I have plans (#99 & #106) to improve the CLI output so that it's more obvious what's gone wrong when stuff happens.

**Comment by bskinn** [comment]
In the near term, best solution is just to download the objects.inv manually by whatever means, and then load as the local file.

**Comment by flying-sheep** [comment]
OK, great to hear this is known already!

**Comment by bskinn** [comment]
Thought so, it just takes a custom header... in manual testing, [this solution](https://stackoverflow.com/a/3336735/4376000) worked.

I'll get this fix into 2.0.1 as soon as I can; the enhanced CLI output will come later on.

**Comment by bskinn** [comment]
Once fixed, restore flask to trial objects.inv's (undo 7a5eb6c211366c4d075dd69f80c048be3980d785).

Also add h5py objects.inv to trial objects.inv's

**Comment by bskinn** [comment]
Also add nonloc tests for pulling flask and h5py inv files.

**Comment by flying-sheep** [comment]
Great, thank you! Note that if you compare the contents of h5py’s objects.inv, they might change soon (I made a PR so they export their stuff as `h5py.Class` instead of plain `Class`)

**Comment by bskinn** [comment]
&lt;nod&gt;, noted, thanks! I'll just add h5py's inventory as a "can I pull this one down?" sanity check, then, rather than using it for detailed tests on the content.

**Comment by bskinn** [comment]
Will get the 2.0.1 release cut as soon as I can manage it. :+1:

**Comment by flying-sheep** [comment]
Awesome, thanks!

**Comment by bskinn** [comment]
v2.0.1 is up on PyPI -- lemme know how it works!

**Comment by flying-sheep** [comment]
Nice, works flawlessly now, thank you!
