### ISSUE TITLE
Deprecation warning from `attr`

### ISSUE THREAD

**Issue by mortenvp** [bskinn/sphobjinv#107]
Hi,
Getting this warning:

```
virtualenv-97d4f4/lib/python3.7/site-packages/sphobjinv/inventory.py:106
  /home/mvp/dev/steinwurf/versjon/virtualenv-97d4f4/lib/python3.7/site-packages/sphobjinv/inventory.py:106: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
    @attr.s(slots=True, cmp=False)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Don't think it has been reported before.

**Comment by bskinn** [comment]
Yup, this is a new warning here. @hynek (& co?) have been working on some API changes, [including this one](https://github.com/python-attrs/attrs/issues/487#issuecomment-517645043)... looks like those are moving forward.

What attrs version do you have installed in that virtualenv?

**Comment by bskinn** [comment]
Looks like it was deprecated in 19.2 -- really not sure why the warning isn't showing up in CI. :-(

**Comment by bskinn** [comment]
Ooooh. Unless the first import of a module happens inside a fixture or test function/etc. (i.e., if a module/packages is imported at the test module scope), it appears that pytests warning-catching machinery can't see it.

I had to add a [new, ~dedicated tox environment](https://github.com/bskinn/sphobjinv/commit/186ac2bc2458c66fc3e95086aa9ab47b379c1d23#diff-b91f3d5bd63fcd17221b267e851608e8R67-R71) in order for the warning to be visible to CI.

I think I've got it fixed.

**Comment by bskinn** [comment]
Will get the 2.0.1 release cut as soon as I can manage it. :+1:

**Comment by mortenvp** [comment]
Awesome :+1:

**Comment by bskinn** [comment]
v2.0.1 is up on PyPI -- lemme know how it works!

**Comment by mortenvp** [comment]
Warning seems to have disappeared - great work! and thanks!
