### ISSUE TITLE
empty version (or project (?)) cause regex matching crash

### ISSUE THREAD

**Issue by svenevs** [bskinn/sphobjinv#85]
Found what I think is a bug in the header parsing.  This [project commented out their version number](https://github.com/uxsolutions/bootstrap-datepicker/blob/9252578f279ace3f624c064e7a239aeaae96f005/docs/conf.py#L21) resulting in an empty `Version` in the header to the `objects.inv`:

```console
sven:/tmp> wget https://bootstrap-datepicker.readthedocs.io/en/master/objects.inv
sven:/tmp> head -4 objects.inv 
# Sphinx inventory version 2
# Project: bootstrap-datepicker
# Version: 
# The remainder of this file is compressed using zlib.
sven:/tmp> sphobjinv convert plain objects.inv 
 

Error: Unrecognized file format
```

If you do it directly, you get information that seems to mean that you assume `Version` and `Project` actually have values after them (and apparently they don't need to):

```python
>>> import sphobjinv as soi
>>> inv = soi.Inventory('objects.inv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<attrs generated init d264050f79466679381c6c61e7053ac5e806eac0>", line 16, in __init__
  File "/usr/local/lib/python3.6/site-packages/sphobjinv/inventory.py", line 365, in __attrs_post_init__
    self._general_import()
  File "/usr/local/lib/python3.6/site-packages/sphobjinv/inventory.py", line 598, in _general_import
    import_errors[st]):
  File "/usr/local/lib/python3.6/site-packages/sphobjinv/inventory.py", line 612, in _try_import
    p, v, o = import_fxn(src)
  File "/usr/local/lib/python3.6/site-packages/sphobjinv/inventory.py", line 659, in _import_plaintext_fname
    return self._import_plaintext_bytes(b_plain)
  File "/usr/local/lib/python3.6/site-packages/sphobjinv/inventory.py", line 629, in _import_plaintext_bytes
    b_res = pb_version.search(b_str).group(HeaderFields.Version.value)
AttributeError: 'NoneType' object has no attribute 'group'
```

I _think_ you want to change `.+` to be `.*`?

https://github.com/bskinn/sphobjinv/blob/11db748f5e31145ee7ec97d5436ee50aeadc0bc4/sphobjinv/re.py#L42

https://github.com/bskinn/sphobjinv/blob/11db748f5e31145ee7ec97d5436ee50aeadc0bc4/sphobjinv/re.py#L51

And then it will return you empty strings?

**Comment by bskinn** [comment]
Never thought anybody'd build docs without a version! 

You're right, that regex for `version` will definitely need to be changed, as you indicated -- will be interesting to see how deep into the codebase that assumption runs.

If Sphinx allows an empty `project`, then yeah, that'll need to be changed, too.


Thanks for reporting this! I'll get a bugfix update out as soon as I can.

**Comment by bskinn** [comment]
On a quick test, it looks like Sphinx automatically sets `project = "Python"` if it is not defined in `conf.py`. I'll make a more thorough test of Sphinx versions back through ~1.0 to be sure, though.

So, I think only the possibility of a blank `version` needs to be accounted for.

**Comment by svenevs** [comment]
> Never thought anybody'd build docs without a version!

Hehehehe.  Bugs like this are kind of fun though, I had no idea sphinx defaulted to `project = "Python"`.  Seems like you've got this under wraps, but let me know if you want any testing from me!  This project has served me very well over the years :slightly_smiling_face:

**Comment by bskinn** [comment]
Keep an eye out for a `v2.0.1rc1` release here soon, it'll get this fix out there before I take care of the `stdio-mgr` problem.  `pip install -U --pre sphobjinv` should grab it once I get it up to PyPI.

**Comment by bskinn** [comment]
v2.0.1rc1 is published, @svenevs

**Comment by bskinn** [comment]
Apologies for this fix sitting on `rc1` for most of a year, @svenevs -- FYI, a final v2.0.1 is now up on PyPI.
